# -*- coding: utf-8 -*-
"""Overview of Colaboratory Features

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/basic_features_overview.ipynb
"""

#Herança

#Criando a classe animal - Super-Classe
class animal()
  def __init__(self):
    print('Aniaml criado')

  def Identif(self):
    print("Animal")

  def comer(self):
    print('Comendo')

#Criando a classe Cachorro - Sub-Classe
class Cachorro(animal)

    def __init__(self):
      Animal.__init__(self):
      print('Objeto Cachorro criado')

    def Identif(self):
      print('Cachorro')

    def latir(self):
      print('Au Au')

#Criando um objeto (Instanciando a classe)
rex = Cachorro()#Nesse caso será usado o Identif da classe cachorro

#Executando o método da classe Cachorro (sub-classe)
rex.Identif()

#Executando o método da classe Cachorro (super-classe)
rex.comer()

#Executando o método da classe Cachorro (sub-classe)
rex.latir()