# -*- coding: utf-8 -*-
"""Overview of Colaboratory Features

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/basic_features_overview.ipynb
"""

# Commented out IPython magic to ensure Python compatibility.
#Métodos Especiais
#Exemplo: __init__ , __delattr__ , __str__

#Criando a classe livro
class Livro():
  def __init__(self,titulo,autor,paginas):
    print('Livro criado')
    self.titulo = titulo
    self.autor = autor
    self.paginas = paginas

  def __str__(self):#__str__ retorna um texto
    return "Titulo: %s , autor: %s, páginas: %s " \
#   %(self.titulo, self.autor, self.paginas)

  def __len__(self):# retorna
    return self.paginas

  def len (self):
    return print('Páginas do livro com método comum: ', self.paginas)

livro1 = Livro("Os Lusíadas", "Luis de Camoões", 8816)

# Métodos especiais
print(livro1)# O método __str__ pe chamado quando usa-se o print

str(livro1)

len(livro1)#Método especial

livro1.len()#Método criado

del livro1.paginas#Apaga o atributo

hasattr(livro1,'paginas')