# -*- coding: utf-8 -*-
"""Overview of Colaboratory Features

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/basic_features_overview.ipynb
"""

#Métodos

#Criando uma classe chamada circulo

class Circulo:
  
  #O valor de pi é constante
  pi = 3.14

  #Quando um objeto desta classe dor criado, este método será executado e o 
  # valor default do raio será 5.
  def __init__(self, raio = 5):
    self.raio = raio

  #Esse método calcula a área. Self utiliza os atributos deste mesmo objeto
  def area(self):
    return (self.raio * self.raio) * Circulo.pi

  #Método para gerar um novo raio
  def setRaio (self, novo_raio):
    self.raio = novo_raio
   
  #Método para obter o raio do circulo
  def getRaio(self):
    return self.raio

#Criando o objeto circ. Uma instancia da classe Circulo()
  circ = circulo()

circ.getRaio()

circ = circulo(7)

#Imprimindo o raio
print('O raio é: ', circ.getRaio())

#Imprimindo a area
print('Area igual a: ', circ.area())

#Gerando um novo valor para o raio do circulo
circ.setRaio(3)

# Imprimindo o novo raio
print('Novo raio igual a: ',circ.getRaio())